name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

change-template: '- $TITLE (#$NUMBER)'

# Only add to the draft release when a PR has one of these labels
include-labels:
  - 'major'
  - 'minor'
  - 'patch'
  - 'chore'

# This is how we determine the release version -- using labels. For example,
# when the "release-minor" label is used, the drafter knows to bump up to a new
# minor version.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
      - 'chore' # allow our chore PRs to just be patches too
  default: patch

# What our Release Summary will look like. If no draft has been created, then
# this will be used, otherwise $CHANGES just gets addedd.
template: |
  ## Release Summary

  $CHANGES
  
