#! /usr/bin/env bash

(

  command="$1"

  if [ -z $command ]; then
    echo -e "Usage: generate <argument>"
    echo -e "\nArguments\n"
    echo -e "  private-key   Generate a private key"
    echo

    exit 1
  fi

  shift

  tsx ./scripts/ts/generate.ts $command $@
)
