#! /usr/bin/env bash

(
  command="$1"

  if [ -z $command ]; then
    echo -e "Usage: process <command> [ options ]"
    echo -e "\nCommands\n"
    echo -e "  compile       Compile a process' filesystem into a single file"
    echo -e "  connect       Connect to a process"
    echo -e "  deploy        Deploy a process"
    echo

    exit 1
  fi

  shift

  if [ $command == "connect" ]; then

    if [ -z $1 ]; then
      echo -e "Usage: process connect <config-key>\n"
      exit 1
    fi

    aos_connect_args=$(tsx ./scripts/ts/process.ts connect $1)

    if [ $? == 1 ]; then
      echo -e "$aos_connect_args\n"
      exit 1
    fi

    echo -e "\nConnecting using the following command and args: \n$aos_connect_args\n"

    eval $aos_connect_args
  fi

  tsx ./scripts/ts/process.ts $command $@
)
